services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "TestCluster"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_RACK: "rack1"